version: "3.7"

networks:
  mojaloop-net:
    name: mojaloop-net

services:
  reporting-hub-bop-trx-ui:
    container_name: reporting-hub-bop-trx-ui
    image: mojaloop/reporting-hub-bop-trx-ui
    build:
      context: .
      cache_from:
        - mojaloop/reporting-hub-bop-trx-ui
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:3009/
      - REACT_APP_MOCK_API=true
    ports:
      - "8082:8082"
    networks:
      - mojaloop-net
    healthcheck:
      test: wget -q http://172.17.0.1:8082 -O /dev/null || exit 1
      timeout: 20s
      retries: 30
      interval: 15s
