resources:
  - github.com/partiallyordered/mojaloop-kustomize/base/nginx-ingress-controller?ref=ee2ffcc2588dcefda74ed6b4f2e47a7388f67f4e
  - github.com/partiallyordered/mojaloop-kustomize/base/mojaloop/central?ref=3903827ee6b00e8efdca9a39d3fe0774b27e93e3
  - github.com/partiallyordered/voodoo-doll/kubernetes?ref=ad96349ef8fe91a422377be8f53aea56aee60c8e
  - secret_copy.yaml
  - ing.yaml
  - ml_adapter_sidecar_config.yaml
  - central_ledger_sidecar_config.yaml

configMapGenerator: []

patches: []
#- target:
#    kind: Deployment
#    name: ml-api-adapter-service
#  path: patch_adapter_event_sidecar.yaml
#- target:
#    kind: Deployment
#    name: centralledger-service
#  path: patch_ledger_event_sidecar.yaml
