apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting-hub-bop-trx-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: reporting-hub-bop-trx-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reporting-hub-bop-trx-ui
    spec:
      containers:
        - name: app
          image: ghcr.io/mojaloop/reporting-hub-bop-trx-ui:v0.0.0
          ports:
            - containerPort: 8082
          env:
            - name: REACT_APP_API_BASE_URL
              value: /reporting-api
